name: 'Set Up Repository'
description: 'Clone the code and install dependencies'
inputs:
  python-version:
    description: 'The version of python to use'
    default: '3.11'
  fetch-depth:
    description: 'The git clone fetch depth'
    default: 1
runs:
  using: "composite"
  steps:
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}
      
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -e .
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
